### ISSUE TITLE
Add Theano, CNTK, and Torch

### ISSUE THREAD

**Issue by iamaziz** [hunkim/DeepLearningStars#2]
Cool repo 👍  thanks for putting it together !! 
Pls add these to the list
https://github.com/Theano/Theano
https://github.com/Microsoft/CNTK 
https://github.com/torch/torch7

**Comment by hunkim** [comment]
Done and README.md is updated. If you know more cool deep learning projects, feel free to send a pull request to list.txt directly.

Cheers!
